import assert from "node:assert/strict";
import test from "node:test";
import { buildExternalSnapshot, buildSemanticDiff, parseJotunnPieces, parseJotunnRecipes } from "../data/external-catalog.ts";
import { buildExternalClassification, nameSimilarity } from "../data/external-classification.ts";

const recipeHtml = `
  <p>This file is automatically generated from Valheim 0.221.12 using JotunnDoc.</p>
  <table><tbody><tr>
    <td>Recipe_StoneAxe</td><td>asset-recipe</td><td>Stone axe</td><td>1</td>
    <td>Level 1:<ul><li>5 Wood</li><li>4 Stone</li></ul>Level 2:<ul><li>2 Stone</li></ul>Level 3:<ul><li>4 Stone</li></ul>Level 4:<ul><li>6 Stone</li></ul></td>
  </tr><tr><td>Recipe_Null</td><td>x</td><td>NULL</td><td>1</td><td><ul></ul></td></tr></tbody></table>`;

const pieceHtml = `
  <p>This file is automatically generated from Valheim 0.221.12 using the JotunnDoc mod.</p>
  <table><tbody><tr>
    <td>piece_fixture<br><img src="piece.png"></td><td>asset-piece</td><td>$piece_fixture</td><td>Fixture bench</td><td>Fixture</td>
    <td><ul><li>10 Wood</li></ul></td><td>Wood</td>
  </tr></tbody></table>`;

test("normaliza recetas y piezas de Jötunn sin conservar HTML", () => {
  const parsedRecipe = parseJotunnRecipes(recipeHtml);
  const parsedPiece = parseJotunnPieces(pieceHtml);
  assert.equal(parsedRecipe.gameVersion, "0.221.12");
  assert.equal(parsedRecipe.ignored.nullNames, 1);
  assert.deepEqual(parsedRecipe.entries[0].levels[0].materials, [{ nameEn: "Wood", amount: 5 }, { nameEn: "Stone", amount: 4 }]);
  assert.deepEqual(parsedPiece.entries[0], {
    sourceKind: "piece", externalId: "piece_fixture", assetId: "asset-piece", itemNameEn: "Fixture bench", outputAmount: 1,
    levels: [{ targetLevel: 1, materials: [{ nameEn: "Wood", amount: 10 }] }],
  });
});

test("rechaza un snapshot compuesto por versiones externas distintas", () => {
  assert.throws(() => buildExternalSnapshot(recipeHtml, pieceHtml.replace("0.221.12", "0.222.1")), /no corresponden a la misma versión/);
});

test("compara por identidad inglesa y campos funcionales sin aplicar cambios", () => {
  const snapshot = buildExternalSnapshot(recipeHtml, pieceHtml, "2026-08-12T00:00:00.000Z");
  const diff = buildSemanticDiff(snapshot, "2026-08-12T00:00:01.000Z");
  assert.equal(diff.summary.matched, 1);
  assert.equal(diff.summary.unchanged, 1);
  assert.equal(diff.summary.modified, 0);
  assert.ok(diff.externalOnly.some((entry) => entry.itemNameEn === "Fixture bench"));

  snapshot.entries[0].outputAmount = 2;
  const changed = buildSemanticDiff(snapshot);
  assert.equal(changed.summary.modified, 1);
  assert.deepEqual(changed.modified[0].changes[0], { field: "outputAmount", local: 1, external: 2 });
});

test("resuelve variantes compactas de nombres de materiales externos", () => {
  const snapshot = buildExternalSnapshot(recipeHtml, pieceHtml, "2026-08-12T00:00:00.000Z");
  snapshot.entries[0].levels[0].materials[0].nameEn = "Finewood";
  const diff = buildSemanticDiff(snapshot);
  assert.equal(diff.summary.unresolvedMaterials, 0);
  assert.equal(diff.modified[0].changes[0].field, "materials");
});

test("clasifica candidatos externos con razones y conserva los casos dudosos", () => {
  const snapshot = buildExternalSnapshot(recipeHtml.replace("Recipe_StoneAxe", "Recipe_AxeFixture").replace("Stone axe", "Fixture War Axe"), pieceHtml, "2026-08-12T00:00:00.000Z");
  snapshot.entries.push({
    sourceKind: "recipe", externalId: "Recipe_Bronze", assetId: "bronze", itemNameEn: "Bronze", outputAmount: 1,
    levels: [{ targetLevel: 1, materials: [{ nameEn: "Copper", amount: 2 }, { nameEn: "Tin", amount: 1 }] }],
  });
  const report = buildExternalClassification(snapshot);
  assert.equal(report.totals.uniqueExternalNames, 3);
  assert.equal(report.classifications.find((entry) => entry.itemNameEn === "Fixture War Axe")?.classification, "functional_candidate");
  assert.equal(report.classifications.find((entry) => entry.itemNameEn === "Bronze")?.classification, "existing_material");
  assert.equal(report.classifications.find((entry) => entry.itemNameEn === "Fixture bench")?.classification, "manual_review");
  assert.ok(report.classifications.every((entry) => entry.reason.length > 0));
  assert.equal(nameSimilarity("Leather Trousers", "Leather pants"), 1 / 3);
});

test("excluye herramientas internas que no son objetos publicados", () => {
  const snapshot = buildExternalSnapshot(recipeHtml, pieceHtml, "2026-08-12T00:00:00.000Z");
  snapshot.entries[0].itemNameEn = "Stone Pickaxe";
  snapshot.entries[0].externalId = "Recipe_PickaxeStone";
  snapshot.entries.push({ ...structuredClone(snapshot.entries[0]), itemNameEn: "[item_torchmist]", externalId: "Recipe_TorchMist" });
  const report = buildExternalClassification(snapshot);
  assert.ok(report.classifications.filter((entry) => ["Stone Pickaxe", "[item_torchmist]"].includes(entry.itemNameEn))
    .every((entry) => entry.classification === "technical_or_non_catalog"));
});
