import assert from "node:assert/strict";
import test from "node:test";
import { compareVersions, stableVersionFromSteam, versionFromJotunn } from "../data/update-check.ts";

test("compara versiones numéricas sin depender del orden lexicográfico", () => {
  assert.equal(compareVersions("0.221.12", "0.221.9"), 1);
  assert.equal(compareVersions("1.0", "1.0.0"), 0);
  assert.equal(compareVersions("0.220.3", "0.221.1"), -1);
});

test("detecta la versión estable y excluye anuncios de Public Test", () => {
  const version = stableVersionFromSteam({ appnews: { newsitems: [
    { title: "Patch 0.222.4 (Public Test)", contents: "Public Test branch" },
    { title: "Patch 0.221.12", contents: "Stable release" },
    { title: "Patch 0.221.9", contents: "Stable release" },
  ] } });
  assert.equal(version, "0.221.12");
});

test("lee la versión declarada por el inventario de Jötunn", () => {
  assert.equal(versionFromJotunn("This file is automatically generated from Valheim 0.221.12 using JotunnDoc."), "0.221.12");
  assert.equal(versionFromJotunn("sin versión"), undefined);
});
