import assert from "node:assert/strict";
import test from "node:test";
import { compareVersions, stableVersionFromSteam, versionFromJotunn } from "../data/update-check.ts";
import { formatUpdateDiagnosis, strictExitCode } from "../data/update-check-format.ts";

test("compara versiones numéricas sin depender del orden lexicográfico", () => {
  assert.equal(compareVersions("0.221.12", "0.221.9"), 1);
  assert.equal(compareVersions("1.0", "1.0.0"), 0);
  assert.equal(compareVersions("0.220.3", "0.221.1"), -1);
});

test("detecta la versión estable y excluye anuncios de Public Test", () => {
  const version = stableVersionFromSteam({ appnews: { newsitems: [
    { title: "Patch 0.222.4 (Public Test)", contents: "Public Test branch" },
    { title: "Patch 0.221.12", contents: "Stable release" },
    { title: "Patch 0.221.9", contents: "Stable release" },
  ] } });
  assert.equal(version, "0.221.12");
});

test("lee la versión declarada por el inventario de Jötunn", () => {
  assert.equal(versionFromJotunn("This file is automatically generated from Valheim 0.221.12 using JotunnDoc."), "0.221.12");
  assert.equal(versionFromJotunn("sin versión"), undefined);
});

test("formatea el diagnóstico y asigna códigos estrictos predecibles", () => {
  const diagnosis = {
    checkedAt: "2026-08-12T17:00:00.000Z",
    current: { appVersion: "1.0.1", catalogVersion: "0.1.20", gameVersion: "0.221.12", dataUpdatedAt: "2026-08-07" },
    latest: { appVersion: "1.0.2", catalogVersion: "0.1.21", stableGameVersion: "0.222.1", jotunnGameVersion: "0.222.1" },
    updates: { app: true, catalog: true, gameData: true },
    status: "review-recommended",
    recommendation: "Revisar la información base.",
    sources: [{ id: "jotunn_recipes", label: "Jötunn", url: "https://example.com", status: "available", version: "0.222.1", detail: "Volcado disponible" }],
  };
  assert.match(formatUpdateDiagnosis(diagnosis), /Estado: REVISIÓN RECOMENDADA/);
  assert.match(formatUpdateDiagnosis(diagnosis), /✓ Jötunn: Volcado disponible/);
  assert.equal(strictExitCode(diagnosis), 1);
  assert.equal(strictExitCode({ ...diagnosis, status: "inconclusive" }), 2);
  assert.equal(strictExitCode({ ...diagnosis, status: "current" }), 0);
});
